name: Fork Safe

on:
  pull_request:
  push:

jobs:
  safe:
    runs-on: ubuntu-latest
    steps:
      - name: Detect Fork
        run: node ./scripts/fork-detect.js

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Tests
        run: npm test
